# Generated by Django 5.1.6 on 2025-09-23 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_prayerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Prayer Request', 'verbose_name_plural': 'Prayer Requests'},
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='approved',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Pending Approval')], default=False),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['approved', 'submitted_at'], name='mainapp_pra_approve_5bb89d_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['submitted_at'], name='mainapp_pra_submitt_b9e62f_idx'),
        ),
    ]
