# Generated by Django 5.1.6 on 2025-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_mediafile_options_alter_prayerrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='prayer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
